# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eConBay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eConBay

  pod "AlamofireImage"
  pod "Parse"

  target 'eConBayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eConBayUITests' do
    # Pods for testing
  end

end
